name: publish

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  check:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
        cache: npm
    - name: Build website
      run: |
        npm ci
        npm run build
  release:
    if: ${{ github.event_name != 'pull_request' && github.repository_owner == 'Callisto13' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
        cache: npm
    - uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.BOT_DEPLOY_KEY }}
    - name: Release to GitHub Pages
      env:
        USE_SSH: true
        GIT_USER: git
        DEPLOYMENT_BRANCH: gh-pages
      run: |
        git config --global user.email "noreply@github.com"
        git config --global user.name "cosmic-bot"
        npm ci
        npm run build
        npm run deploy
